// Render orchestrator: canonical aspect JSON -> self-contained deck HTML.
// Deterministic. No AI. Same JSON always yields the same deck.
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { THEME_CSS } from "./theme.js";
import { GEOMAP_CLIENT_SCRIPT } from "./maps/geomap.js";
import * as routeOptimization from "./templates/route-optimization.js";
import * as travelerProfile from "./templates/traveler-profile.js";
import * as foodDining from "./templates/food-dining.js";
import * as masterItinerary from "./templates/master-itinerary.js";
import * as accommodation from "./templates/accommodation.js";
import * as etiquette from "./templates/etiquette.js";
import * as shopping from "./templates/shopping.js";
import * as cultureMuseums from "./templates/culture-museums.js";
import * as packing from "./templates/packing.js";
import * as dashboard from "./templates/dashboard.js";
import * as flights from "./templates/flights.js";
import * as hotels from "./templates/hotels.js";
import * as generic from "./templates/generic.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const VENDOR = join(__dirname, "../../vendor");

const TEMPLATES = {
  "route-optimization": routeOptimization,
  "traveler-profile": travelerProfile,
  "food-dining": foodDining,
  "master-itinerary": masterItinerary,
  accommodation,
  etiquette,
  shopping,
  "culture-museums": cultureMuseums,
  packing,
  dashboard,
  flights,
  hotels,
  generic
};

export function getTemplate(name) {
  return TEMPLATES[name] || generic;
}

function readVendor(file) {
  return readFileSync(join(VENDOR, file), "utf8");
}

// Build a single self-contained deck. `slides` = [{ templateName, data }].
export function renderDeck(slides, meta = {}) {
  const anyMap = slides.some(s => getTemplate(s.templateName).usesMap);

  const slideHTML = slides.map(s => {
    const tpl = getTemplate(s.templateName);
    return tpl.render(s.data);
  }).join("\n");

  // Only inline the (large) map assets when a slide actually needs a map.
  let mapAssets = "";
  if (anyMap) {
    const d3js = readVendor("d3.min.js");
    const topojsonjs = readVendor("topojson-client.min.js");
    const worldTopo = readVendor("countries-110m.json");
    mapAssets = `
    <script>${d3js}</script>
    <script>${topojsonjs}</script>
    <script>window.WORLD_TOPO = ${worldTopo};</script>
    <script>${GEOMAP_CLIENT_SCRIPT}</script>`;
  }

  const title = meta.title || meta.trip || "Travel Deck";
  const subtitle = meta.subtitle || `${slides.length} slide${slides.length === 1 ? "" : "s"}`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title}</title>
  <style>${THEME_CSS}</style>
</head>
<body>
  <div class="deck-head">
    <h1>${title}</h1>
    <p>${subtitle} · generated by travel-genie pipeline</p>
  </div>
  ${slideHTML}
  ${mapAssets}
</body>
</html>`;
}
